
Resources:
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${file(resources/index.json):table_name}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: role
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: GSI_ROLE
          KeySchema:
            - AttributeName: role
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST