Resources:
  UserClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: ${file(resources/index.json):user_client_name}
      GenerateSecret: false
      UserPoolId: { Ref: UserPool }
      AccessTokenValidity: 5
      IdTokenValidity: 5
      ExplicitAuthFlows:
        - 'ADMIN_NO_SRP_AUTH'
