export enum ERROR_CODES {
  CREATE_USER_FAILED = 'CREATE_USER_FAILED',
  SAVE_ITEM_FAILED = 'SAVE_ITEM_FAILED',
  QUERY_ITEMS_FAILED = 'QUERY_ITEMS_FAILED',
  SIGN_UP_FAILED = 'SIGN_UP_FAILED',
  GET_USER_BY_KEY_FAILED = 'GET_USER_BY_KEY_FAILED',
  SEND_EMAIL_FAILED = 'SEND_EMAIL_FAILED',
  SEND_VERIFY_EMAIL_FAILED = 'SEND_VERIFY_EMAIL_FAILED',
  STORE_VERIFICATION_FAILED = 'SEND_VERIFY_EMAIL_FAILED',
}
