enum ErrorNames {
  FAULT_ADAPTER = 'FAULT_ADAPTER_ERROR',
  FAULT_ENTITY = 'FAULT_ENTITY_ERROR',
  FAULT_INFRASTRUCTURE = 'FAULT_INFRASTRUCTURE_ERROR',
  FAULT_DOMAIN = 'FAULT_DOMAIN_ERROR',
  FAULT_CONTROLLER = 'FAULT_CONTROLLER_ERROR',
  FAULT_EXTERNAL_API = 'FAULT_EXTERNAL_API_ERROR',
}

export default ErrorNames;
