export enum ERROR_CODES {
  CREATE_USER_FAILED = 'CREATE_USER_FAILED',
  CREATE_TABLE_ITEM_FAILED = 'CREATE_TABLE_ITEM_FAILED',
  QUERY_TABLE_ITEMS_FAILED = 'QUERY_TABLE_ITEMS_FAILED',
  DELETE_TABLE_ITEM_FAILED = 'DELETE_TABLE_ITEM_FAILED',
  SIGN_UP_FAILED = 'SIGN_UP_FAILED',
  GET_USER_BY_KEY_FAILED = 'GET_USER_BY_KEY_FAILED',
  SEND_EMAIL_FAILED = 'SEND_EMAIL_FAILED',
  SEND_VERIFY_EMAIL_FAILED = 'SEND_VERIFY_EMAIL_FAILED',
  CREATE_USER_VERIFICATION_FAILED = 'CREATE_USER_VERIFICATION_FAILED',
  DELETE_USER_VERIFICATION_FAILED = 'DELETE_USER_VERIFICATION_FAILED',
  GET_USER_VERIFICATION_FAILED = 'GET_USER_VERIFICATION_FAILED',
}
