export enum ERROR_CODES {
  CREATE_USER_FAILED = 'CREATE_USER_FAILED',
  GET_USER_BY_KEY_FAILED = 'GET_USER_BY_KEY_FAILED',
  SEND_EMAIL_FAILED = 'SEND_EMAIL_FAILED',
  SEND_VERIFY_EMAIL_FAILED = 'SEND_VERIFY_EMAIL_FAILED',
}
